import { load } from '@netflix/x-test/x-test.js';

load('./test-parser.html');
load('./test-template-engine.html');
load('./test-analysis-errors.html');
load('./test-initialization-errors.html');
load('./test-attribute-changed-errors.html');
load('./test-element-upgrade.html');
load('./test-render.html');
load('./test-render-root.html');
load('./test-styles.html');
load('./test-basic-properties.html');
load('./test-initial-properties.html');
load('./test-default-properties.html');
load('./test-read-only-properties.html');
load('./test-internal-properties.html');
load('./test-reflected-properties.html');
load('./test-computed-properties.html');
load('./test-observed-properties.html');
load('./test-listeners.html');
load('./test-property-deletion.html');
load('./test-scratch.html');
