# Test flow triggered by other workflows.
name: Test
on: [workflow_call]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '22.14'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run lint
      - run: npm run type
      - run: git diff --exit-code
      - run: npm start &
      - run: sleep 2
      - run: npm test
